---
- name: Check if Kind {{ kind_version }} already downloaded
  stat:
    path: "{{ inventory_dir }}/.resources/kind-{{ kind_version }}"
  register: kind_binary

- name: "Create .resources directory if does not exist: {{ inventory_dir }}/.resources/"
  ansible.builtin.file:
    path: "{{ inventory_dir }}/.resources/"
    state: directory
    mode: '0755'

- name: Download Kind {{ kind_version }} binary
  shell: "curl -Lo kind-{{ kind_version }} {{ kind_url }}"
  args:
    chdir: "{{ inventory_dir }}/.resources"
    warn: false
  when: kind_binary.stat.exists == false

- name: Make Kind {{ kind_version }} binary executable
  ansible.builtin.file:
    path: "{{ inventory_dir }}/.resources/kind-{{ kind_version }}"
    state: file
    mode: '0755'
