---
- name: Install Knative (CRDS and Core)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ knative_serving_crds }}"
    - "{{ knative_serving_core }}"


- name: Wait for KNative Serving deployments (CRDS and Core)
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    wait_condition:
      type: Available
      status: "True"
      reason: MinimumReplicasAvailable
    name: "{{ item }}"
    namespace: knative-serving
    wait_timeout: 360
  with_items: "{{ knative_serving_wait_for_deployments_core_list }}"
  when: knative_serving_wait_for_deployments | bool


- name: Install Knative (Istio Networking)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', knative_serving_net_istio, split_lines=False) }}"


- name: Wait for KNative Serving deployments (Istio Networking)
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    wait_condition:
      type: Available
      status: "True"
      reason: MinimumReplicasAvailable
    name: "{{ item }}"
    namespace: knative-serving
    wait_timeout: 360
  with_items: "{{ knative_serving_wait_for_deployments_net_list }}"
  when: knative_serving_wait_for_deployments | bool
