namespace: "seldonio"
name: "k8s"
version: "0.2.0-dev"
readme: "README.md"
authors:
    - "Seldon Technologies Ltd. <hello@seldon.io>"
dependencies:
    "community.kubernetes": "<2.0.0"
    "community.docker": "*"
    "community.crypto": "*"
license:
    - "Apache 2.0"
tags:
    - seldon
    - kubernetes
    - ecosystem
repository: "https://www.github.com/seldonio/ansible-tools"
build_ignore:
    - .resources
