---
- name: Check if certificate paths are set
  set_fact:
    certificate_paths_provided: "{{ (istio_ssl_certificates.server_crt_path is defined) and (istio_ssl_certificates.server_key_path is defined) and (istio_ssl_certificates.server_crt_path is not none) and (istio_ssl_certificates.server_key_path is not none)}}"

- name: Check istio_ssl configuration
  fail:
    msg: "When not using self signed certificates the certificates paths must be provided."
  when: (not istio_use_self_signed_ca | bool) and (not certificate_paths_provided | bool)


- name: Wait for External IP Address to be ready
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Service
    name: istio-ingressgateway
    namespace: istio-system
    wait: yes
    wait_timeout: 360
  register: istio_web_service
  until: >
    'ingress' in istio_web_service.resources[0].status.loadBalancer and
    istio_web_service.resources[0].status.loadBalancer.ingress[0].ip != ""
  retries: 20
  delay: 5

- name: Set fact about Istio Ingress Gateway External IP
  set_fact:
    istio_external_ip: "{{ istio_web_service.resources[0].status.loadBalancer.ingress[0].ip }}"


- name: Create temporary certificates directory
  ansible.builtin.tempfile:
    state: directory
    suffix: certificate
  register: tmp_cert_dir
  when: istio_use_self_signed_ca | bool


- name: Generate Self Signed Server SSL Certs from Self Signed CA
  include: self_signed.yaml
  when: istio_use_self_signed_ca | bool

- name: Set fact about Server SSL Certs Paths (self-signed certificates)
  set_fact:
    server_crt_path: "{{ tmp_cert_dir.path + '/server.crt' }}"
    server_key_path: "{{ tmp_cert_dir.path + '/server.key' }}"
  when: istio_use_self_signed_ca | bool

- name: Set fact about Server SSL Certs Paths (not self-signed certificates)
  set_fact:
    server_crt_path: "{{ istio_ssl_certificates.server_crt_path }}"
    server_key_path: "{{ istio_ssl_certificates.server_key_path }}"
  when: not (istio_use_self_signed_ca | bool)


- name: Create Istio Ingressgateway SSL Certs Secret
  community.kubernetes.k8s:
    state: present
    namespace: istio-system
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: istio-ingressgateway-certs
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file', server_crt_path) | b64encode }}"
        tls.key: "{{ lookup('file', server_key_path) | b64encode }}"


- name: Remove temporary certificates directory
  ansible.builtin.file:
    path: "{{ tmp_cert_dir.path }}"
    state: absent
  when: (istio_use_self_signed_ca | bool) and tmp_cert_dir.path is defined
