---
- name: Check if Istio {{ istio_version }} already downloaded.
  stat:
    path: "{{ inventory_dir }}/.resources/istio-{{ istio_version }}"
  register: istio_directory


- name: "Create .resources directory if does not exist: {{ inventory_dir }}/.resources/"
  ansible.builtin.file:
    path: "{{ inventory_dir }}/.resources/"
    state: directory
    mode: '0755'


- name: Download Istio {{ istio_version }}
  shell: "curl -L https://istio.io/downloadIstio | ISTIO_VERSION={{ istio_version }} sh -"
  args:
    chdir: "{{ inventory_dir }}/.resources"
    warn: false
  when: istio_directory.stat.exists == false


- name: Install Istio {{ istio_version }}
  shell: "./bin/istioctl install --set profile=default -y"
  args:
    chdir: "{{ inventory_dir }}/.resources/istio-{{ istio_version }}"


- name: Verify Install Istio {{ istio_version }}
  shell: "./bin/istioctl verify-install"
  args:
    chdir: "{{ inventory_dir }}/.resources/istio-{{ istio_version }}"
  when: istio_verify_install | bool


- name: Create Seldon Gateway
  community.kubernetes.k8s:
    state: present
    template: templates/gateway.yaml.j2
  when: istio_create_seldon_gateway | bool


- name: Configure certificates
  block:
    - name: Create temporary certificates directory
      ansible.builtin.tempfile:
        state: directory
        suffix: certificate
      register: tmp_cert_dir
    - name: Generate certificates
      include: certificates.yaml
  always:
    - name: Remove temporary certificates directory
      ansible.builtin.file:
        path: "{{ tmp_cert_dir.path }}"
        state: absent
      when: tmp_cert_dir.path is defined
  when: >
    istio_ssl.enabled | bool
