---
gitea_namespace: gitea-system
gitea_version: 4.0.0

gitea_values: {}
gitea_values_files: []

gitea_port: "3000"

gitea_use_istio: true
gitea_create_virtualservice: "{{ gitea_use_istio }}"
gitea_virtualservice_gateway: istio-system/seldon-gateway

gitea_wait_for_deployments: true
