---
knative_eventing_version: v0.22.0
knative_eventing_download_url: "https://github.com/knative/eventing/releases/download"

knative_eventing_crds: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/eventing-crds.yaml"
knative_eventing_core: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/eventing-core.yaml"
knative_eventing_channel: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/in-memory-channel.yaml"
knative_eventing_broker: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/mt-channel-broker.yaml"

knative_eventing_wait_for_deployments: true

knative_eventing_create_default_broker: false
knative_eventing_default_broker_name: default
knative_eventing_default_broker_namespace: default
