---
- name: Install Knative Eventing
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ knative_eventing_crds }}"
    - "{{ knative_eventing_core }}"
    - "{{ knative_eventing_channel }}"
    - "{{ knative_eventing_broker }}"
  when: (knative_eventing_workaround_issue_189 | bool) == false

- name: Install Knative Eventing (direct kubectl to workarond issue 189)
  shell: "kubectl apply -f {{ item }}"
  with_items:
    - "{{ knative_eventing_crds }}"
    - "{{ knative_eventing_core }}"
    - "{{ knative_eventing_channel }}"
    - "{{ knative_eventing_broker }}"
  when: knative_eventing_workaround_issue_189 | bool

- name: Wait for KNative Eventing deployments
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    wait_condition:
      type: Available
      status: "True"
      reason: MinimumReplicasAvailable
    name: "{{ item }}"
    namespace: knative-eventing
    wait_timeout: 360
  with_items: "{{ knative_eventing_wait_for_deployments_list }}"
  when: knative_eventing_wait_for_deployments | bool

- name: Add tag resolution disabled repositories
  kubernetes.core.k8s:
    kind: ConfigMap
    name: config-deployment
    namespace: knative-serving
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config-deployment
        namespace: knative-serving
      data:
        registriesSkippingTagResolving: kind.local,ko.local,dev.local

- name: Create default broker
  include: create_broker.yaml
  when: knative_eventing_create_default_broker | bool
