---
- name: "Create {{ elastic_opendistro_secret_name }} secret"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ item }}"
    template: templates/elastic_credentials_secret.yaml.j2
  with_items:
    - "{{ seldon_system_namespace }}"
    - "{{ elastic_opendistro_namespace }}"
