---
- name: Create MinIO Secret (rclone storage initializer format)
  kubernetes.core.k8s:
    state: present
    namespace: "{{ item }}"
    template: templates/minio_rclone_secret.yaml.j2
  with_items: "{{ minio_secret_namespaces }}"
  when: minio_rclone_secret_name is not none

- name: Create MinIO Secret (kfserving storage initializer format)
  kubernetes.core.k8s:
    state: present
    namespace: "{{ item }}"
    template: templates/minio_kfserving_secret.yaml.j2
  with_items: "{{ minio_secret_namespaces }}"
  when: minio_kfserving_secret_name is not none
